### ISSUE TITLE
interSpace not working

### ISSUE THREAD

**Issue by AdrianHyj** [xornorik/SVPinView#27] opened 2019-05-20 11:33 UTC
I have init the pinview ..
`pinView.frame = CGRect(x: 15, y: 150, width: frame.size.width - 30, height: 44)`
and set it's interSpace to 20
`pinView.interSpace = 20`
it turns out it didn't center, and the space is not 20 at all
<img width="533" alt="image" src="https://user-images.githubusercontent.com/7114108/58018700-19094880-7b36-11e9-96bd-0543a6f3bd67.png">

**Comment by xornorik** [comment] 2019-10-09 12:20
Hi @AdrianHyj, the interspace property did not apply because the applied constraints are not satisfiable i.e *(interspace * (number of digits - 1)) + (2 * Applied padding for SVPinView) > (Width of the screen)*. 
The Default behaviour of SVPinView is to fit all the digits on the screen without the need for scroll, so if the given constraints cannot be applied, the interspace becomes 0 and they become left aligned. 
I can perhaps make this behaviour more evident at compile time so it does not seem like unexpected behaviour. Will plan this for the next release.
 
Closing this for now. Please feel free to open it again in case I have misunderstood the issue or you have any suggestions.

Thanks!

**Comment by AdrianHyj** [comment] 2019-10-14 06:58
ok, Thankyou.

**Closed** 2020-03-29 17:23 UTC
Labels: bug
